{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinel.fullname" . }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
type: Opaque
stringData:
  influxdbToken: {{ .Values.secrets.influxdbToken | quote }}
  rabbitmqUsername: {{ .Values.secrets.rabbitmqUsername | quote }}
  rabbitmqPassword: {{ .Values.secrets.rabbitmqPassword | quote }}
  redisPassword: {{ .Values.secrets.redisPassword | quote }}
  webhookSecret: {{ .Values.secrets.webhookSecret | quote }}
{{- end }}
